# Generated by Django 3.2.9 on 2021-12-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
